exclude: |
  (?x)(
      ^\.venv.*?/
    | ^\.mypy_cache/
    | ^\.pytest_cache/
    | ^\.ruff_cache/
    | ^data/
    | ^reports/
    | ^switchboard\.egg-info/
    | ^docs/media/.+\.(gif|mp4|mov|png)$
  )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - streamlit
          - pytest
          - types-requests
          - types-PyYAML
