version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    environment:
      - APP_ENV=docker
      - OPA_URL=http://opa:8181
      - SWITCHBOARD_USE_OPA=true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - opa
      - otel-collector
    volumes:
      - ./:/workspace

  demo-agent:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.demo_agent
    environment:
      - SWITCHBOARD_API_URL=http://api:8000
      - SWITCHBOARD_APPROVALS_URL=http://approvals-ui:8501
    depends_on:
      - api
    volumes:
      - ./:/workspace

  mcp-server:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.mcp
    environment:
      - SWITCHBOARD_API_URL=http://api:8000
    ports:
      - "8081:8081"
    volumes:
      - ./:/workspace

  approvals-ui:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.approvals_ui
    environment:
      - SWITCHBOARD_API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: switchboard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: switchboard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opa:
    image: openpolicyagent/opa:0.63.0
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    volumes:
      - ./switchboard/policy:/policies
    ports:
      - "8181:8181"

  otel-collector:
    image: otel/opentelemetry-collector:0.101.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./infra/docker/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"

volumes:
  postgres-data:
