FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY pyproject.toml README.md ./
RUN pip install --upgrade pip && pip install ".[dev]"

COPY apps/demo_agent ./apps/demo_agent
COPY switchboard ./switchboard

CMD ["python", "-m", "apps.demo_agent.main"]
