FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV OPA_URL=http://opa:8181
ENV SWITCHBOARD_USE_OPA=true

WORKDIR /app

COPY pyproject.toml README.md ./
RUN pip install --upgrade pip && pip install ".[dev]"

COPY switchboard ./switchboard
COPY scripts ./scripts

EXPOSE 8000

CMD ["uvicorn", "switchboard.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
