FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV SWITCHBOARD_API_URL=http://api:8000
ENV SWITCHBOARD_APPROVALS_URL=http://approvals-ui:8501

WORKDIR /app

COPY pyproject.toml README.md ./
RUN pip install --upgrade pip && pip install ".[dev]"

COPY apps/demo_agent ./apps/demo_agent
COPY switchboard ./switchboard

CMD ["python", "-m", "apps.demo_agent.main"]
