name: Chaos Tests

on:
  workflow_dispatch:

jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -e .[dev]
      - name: Launch stack
        run: |
          docker compose up -d
          sleep 30
      - name: Run chaos scripts
        run: |
          . .venv/bin/activate
          python scripts/chaos/opa_outage.py
          python scripts/chaos/adapter_flap.py || true
          python scripts/chaos/db_outage.py
      - name: Tear down
        if: always()
        run: docker compose down
