name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SWITCHBOARD_APPROVAL_BACKEND: memory
      SWITCHBOARD_ENABLE_TELEMETRY: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint
        run: |
          ruff check .
          black --check .
          mypy .

      - name: Test
        run: pytest

      - name: Tox (py311)
        run: tox

      - name: Coverage
        run: pytest --cov=switchboard --cov-report=term-missing
